import {BrowserProvider,JsonRpcProvider,ContractFactory,Contract,sha256,toUtf8Bytes,isAddress,formatEther} from 'ethers';
const $=id=>document.getElementById(id);
const networks={testnet:{chainId:'0x3c8',chainName:'BOT Chain Testnet',rpc:'https://rpc.bohr.life',explorer:'https://scan.bohr.life'},mainnet:{chainId:'0x2a5',chainName:'BOT Chain Mainnet',rpc:'https://rpc.botchain.ai',explorer:'https://scan.botchain.ai'}};
const artifact=await fetch('/contract.json').then(r=>{if(!r.ok)throw Error('合约资源加载失败');return r.json()});
let walletProvider,signer,account,busy=false;
const evidence={testnet:{},mainnet:{}};
const net=()=>networks[$('network').value];
const current=()=>evidence[$('network').value];
function message(text){$('status').textContent=text;$('feedback').hidden=false;$('feedback').textContent=text;}
function render(){const e=current();$('contract').value=e.contract||'';$('links').replaceChildren();for(const [key,label,path] of [['contract','合约地址','address'],['deploymentTx','部署交易','tx'],['attestationTx','存证交易','tx']])if(e[key]){const a=document.createElement('a');a.href=net().explorer+'/'+path+'/'+e[key];a.textContent=label+' · '+e[key].slice(0,10)+'…';a.target='_blank';a.rel='noopener';$('links').append(a);} }
function digestOf(text){if(!text.trim())throw Error('请先填写报告原文');return sha256(toUtf8Bytes(text));}
function address(id){const s=$(id).value.trim();if(!isAddress(s))throw Error('请输入有效的'+(id==='author'?'钱包':'合约')+'地址');return s;}
async function work(fn){if(busy)return;busy=true;document.querySelectorAll('button,select').forEach(b=>b.disabled=true);try{await fn()}catch(e){message('操作未完成：'+(e.shortMessage||e.message||String(e)))}finally{busy=false;document.querySelectorAll('button,select').forEach(b=>b.disabled=false)}}
async function connect(){message('正在请求连接，请检查钱包扩展或钱包 App 中的授权窗口。');if(!window.ethereum)throw Error('未检测到钱包：手机请用钱包 App 内置浏览器打开此网址；电脑请安装并启用 MetaMask 等钱包扩展。');await window.ethereum.request({method:'eth_requestAccounts'});message('钱包已授权，正在切换网络。请检查钱包中的确认请求。');await ensureNetwork();walletProvider=new BrowserProvider(window.ethereum);signer=await walletProvider.getSigner();account=await signer.getAddress();$('wallet').textContent=account;$('author').value=account;$('connect').textContent='钱包已连接';message('钱包已连接，正在读取余额。');const balance=await walletProvider.getBalance(account);message('钱包已连接 · '+net().chainName+' · 余额 '+formatEther(balance)+' BOT');}
async function ensureNetwork(){const n=net();try{await window.ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:n.chainId}]})}catch(e){if(e.code!==4902)throw e;await window.ethereum.request({method:'wallet_addEthereumChain',params:[{chainId:n.chainId,chainName:n.chainName,rpcUrls:[n.rpc],nativeCurrency:{name:'BOT',symbol:'BOT',decimals:18},blockExplorerUrls:[n.explorer]}]});await window.ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:n.chainId}]});}const actual=await window.ethereum.request({method:'eth_chainId'});if(BigInt(actual)!==BigInt(n.chainId))throw Error('钱包网络与所选网络不一致');}
async function writable(){await connect();return signer;}
async function readonly(){const p=new JsonRpcProvider(net().rpc,undefined,{staticNetwork:false});const n=await p.getNetwork();if(n.chainId!==BigInt(net().chainId))throw Error('RPC 网络不匹配');return p;}
$('connect').onclick=()=>work(connect);
$('sample').onclick=()=>{$('report').value='Agent security review / 2026-10-07\n任务：检查示例应用的凭证处理。\n结论：凭证应留在钱包中；前端不收集私钥。\n限制：这是演示文本，未对实际项目进行审计。';$('digest').textContent='尚未生成哈希';};
$('hash').onclick=()=>work(async()=>{$('digest').textContent=digestOf($('report').value);message('内容哈希已在浏览器本地生成，尚未上链。');});
$('copyReport').onclick=()=>{$('verifyReport').value=$('report').value;};
$('contract').onchange=()=>{current().contract=$('contract').value.trim();render();};
$('network').onchange=()=>{signer=null;walletProvider=null;account=null;$('wallet').textContent='请重新连接所选网络';$('connect').textContent='连接钱包';$('verification').textContent='网络已切换，请重新查询。';$('verification').className='result';render();message('已选择 '+net().chainName+'。两个网络的合约与交易分别保存。');};
$('deploy').onclick=()=>work(async()=>{const s=await writable();const gas=await s.estimateGas({data:artifact.bytecode});message('请在钱包确认部署 · 预计 Gas '+gas.toString());const c=await new ContractFactory(artifact.abi,artifact.bytecode,s).deploy();const tx=c.deploymentTransaction();current().deploymentTx=tx.hash;render();message('部署交易已广播，等待确认：'+tx.hash);await c.waitForDeployment();current().contract=await c.getAddress();render();message(net().chainName+' 合约部署成功。现在可提交一次存证。');});
$('attest').onclick=()=>work(async()=>{const addr=address('contract'),digest=digestOf($('report').value);const s=await writable();const c=new Contract(addr,artifact.abi,s);const code=await walletProvider.getCode(addr);if(code==='0x')throw Error('所选网络上的这个地址没有合约');const existing=await c.proofs(account,digest);if(existing>0n)throw Error('此钱包已经存证过这份内容，请直接核验');$('digest').textContent=digest;message('请在钱包确认存证交易');const tx=await c.attest(digest);Object.assign(current(),{contract:addr,author:account,digest,attestationTx:tx.hash});render();message('存证交易已广播，等待确认：'+tx.hash);const receipt=await tx.wait();if(receipt.status!==1)throw Error('交易执行失败');current().blockNumber=receipt.blockNumber;message(net().chainName+' 存证成功。复制报告到核验区可查询时间戳。');});
$('verify').onclick=()=>work(async()=>{const addr=address('contract'),author=address('author'),digest=digestOf($('verifyReport').value);const p=await readonly();if(await p.getCode(addr)==='0x')throw Error('此地址在所选网络上没有合约');const timestamp=await new Contract(addr,artifact.abi,p).proofs(author,digest);$('verification').className='result '+(timestamp>0n?'ok':'bad');$('verification').textContent=timestamp>0n?'找到匹配存证。提交者：'+author+'；链上时间：'+new Date(Number(timestamp)*1000).toLocaleString()+'；内容哈希：'+digest:'未找到匹配存证。请检查原文是否修改、提交者地址、合约地址和所选网络。';message('链上查询完成 · '+net().chainName);});
$('export').onclick=()=>work(async()=>{const e=current();const data={project:'AgentProof',network:net().chainName,chainId:parseInt(net().chainId,16),demo:location.origin,...e,contractLink:e.contract?net().explorer+'/address/'+e.contract:null,deploymentLink:e.deploymentTx?net().explorer+'/tx/'+e.deploymentTx:null,transactionLink:e.attestationTx?net().explorer+'/tx/'+e.attestationTx:null};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='agentproof-'+$('network').value+'-evidence.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message('证据已导出。仅包含真实已产生的地址与交易；未完成字段为空。');});
if(window.ethereum?.on){window.ethereum.on('accountsChanged',()=>{signer=null;account=null;$('wallet').textContent='钱包账户已更改，请重新连接';});window.ethereum.on('chainChanged',()=>{signer=null;walletProvider=null;});}
